/**
 * Mock Data for Recruitment System
 * Dados de exemplo para testar o sistema de recrutamento
 */

import type { Job, Candidate, ApplicationWithDetails, PipelineStage } from '@/types/recruitment';

// =====================================================
// PIPELINE STAGES
// =====================================================

export const mockStages: PipelineStage[] = [
  { id: 'triagem', name: 'Triagem', order: 1, color: '#64748b' },
  { id: 'entrevista_rh', name: 'Entrevista RH', order: 2, color: '#3b82f6' },
  { id: 'teste_tecnico', name: 'Teste Técnico', order: 3, color: '#8b5cf6' },
  { id: 'entrevista_gestor', name: 'Entrevista Gestor', order: 4, color: '#f59e0b' },
  { id: 'proposta', name: 'Proposta', order: 5, color: '#10b981' },
  { id: 'contratado', name: 'Contratado', order: 6, color: '#22c55e' },
];

// =====================================================
// JOBS
// =====================================================

export const mockJobs: Job[] = [
  {
    id: '1',
    company_id: 'company-1',
    title: 'Desenvolvedor Full Stack Sênior',
    code: 'DEV-001',
    description: 'Buscamos desenvolvedor experiente em React e Node.js',
    department: 'Tecnologia',
    location: 'São Paulo - SP',
    employment_type: 'full_time',
    contract_type: 'clt',
    required_skills: ['React', 'Node.js', 'TypeScript', 'PostgreSQL'],
    nice_to_have_skills: ['Next.js', 'GraphQL', 'AWS'],
    education_level: 'Superior Completo',
    experience_years: 5,
    languages: [
      { language: 'Português', level: 'native' },
      { language: 'Inglês', level: 'advanced' },
    ],
    salary_min: 8000,
    salary_max: 12000,
    salary_currency: 'BRL',
    benefits: ['Vale Refeição', 'Vale Transporte', 'Plano de Saúde', 'Home Office'],
    positions_available: 2,
    positions_filled: 0,
    hiring_manager_id: 'user-1',
    recruiters: ['user-2'],
    pipeline_stages: mockStages,
    status: 'open',
    published_at: '2024-01-15T10:00:00Z',
    closed_at: null,
    expires_at: '2024-03-15T23:59:59Z',
    slug: 'desenvolvedor-full-stack-senior',
    is_remote: true,
    is_public: true,
    metadata: {},
    created_at: '2024-01-10T10:00:00Z',
    updated_at: '2024-01-10T10:00:00Z',
    created_by: 'user-1',
    updated_by: null,
  },
  {
    id: '2',
    company_id: 'company-1',
    title: 'Product Designer',
    code: 'DES-001',
    description: 'Designer experiente para liderar projetos de UX/UI',
    department: 'Design',
    location: 'Remoto',
    employment_type: 'full_time',
    contract_type: 'clt',
    required_skills: ['Figma', 'Design Systems', 'UX Research', 'Prototipagem'],
    nice_to_have_skills: ['Motion Design', 'Illustration', 'HTML/CSS'],
    education_level: 'Superior Completo',
    experience_years: 4,
    languages: [{ language: 'Português', level: 'native' }],
    salary_min: 6000,
    salary_max: 10000,
    salary_currency: 'BRL',
    benefits: ['Vale Refeição', 'Plano de Saúde', 'Home Office'],
    positions_available: 1,
    positions_filled: 0,
    hiring_manager_id: 'user-1',
    recruiters: ['user-2'],
    pipeline_stages: mockStages,
    status: 'open',
    published_at: '2024-01-20T10:00:00Z',
    closed_at: null,
    expires_at: '2024-03-20T23:59:59Z',
    slug: 'product-designer',
    is_remote: true,
    is_public: true,
    metadata: {},
    created_at: '2024-01-18T10:00:00Z',
    updated_at: '2024-01-18T10:00:00Z',
    created_by: 'user-1',
    updated_by: null,
  },
];

// =====================================================
// CANDIDATES
// =====================================================

export const mockCandidates: Candidate[] = [
  {
    id: 'cand-1',
    company_id: 'company-1',
    full_name: 'Ana Silva',
    email: 'ana.silva@email.com',
    phone: '(11) 98765-4321',
    location: 'São Paulo - SP',
    linkedin_url: 'https://linkedin.com/in/anasilva',
    portfolio_url: null,
    current_position: 'Desenvolvedora Full Stack',
    current_company: 'Tech Corp',
    experience_years: 6,
    education_level: 'Superior Completo',
    skills: ['React', 'Node.js', 'TypeScript', 'PostgreSQL', 'AWS'],
    languages: [
      { language: 'Português', level: 'native' },
      { language: 'Inglês', level: 'advanced' },
    ],
    resume_url: 'https://example.com/resume-ana-silva.pdf',
    resume_filename: 'ana-silva-cv.pdf',
    cover_letter: null,
    expected_salary_min: 9000,
    expected_salary_max: 12000,
    available_from: '2024-03-01',
    notice_period_days: 30,
    tags: ['senior', 'full-stack', 'react'],
    rating: 5,
    source: 'linkedin',
    source_details: 'Aplicação direta via LinkedIn',
    referred_by: null,
    consent_data_processing: true,
    consent_given_at: '2024-01-15T14:30:00Z',
    data_retention_until: '2025-01-15',
    is_blacklisted: false,
    blacklist_reason: null,
    metadata: {},
    created_at: '2024-01-15T14:30:00Z',
    updated_at: '2024-01-15T14:30:00Z',
    created_by: 'user-2',
    updated_by: null,
  },
  {
    id: 'cand-2',
    company_id: 'company-1',
    full_name: 'Bruno Santos',
    email: 'bruno.santos@email.com',
    phone: '(11) 91234-5678',
    location: 'Rio de Janeiro - RJ',
    linkedin_url: null,
    portfolio_url: null,
    current_position: 'Backend Developer',
    current_company: 'StartupXYZ',
    experience_years: 4,
    education_level: 'Superior Cursando',
    skills: ['Node.js', 'Express', 'MongoDB', 'Docker'],
    languages: [{ language: 'Português', level: 'native' }],
    resume_url: 'https://example.com/resume-bruno-santos.pdf',
    resume_filename: 'bruno-santos-cv.pdf',
    cover_letter: 'Tenho grande interesse na vaga...',
    expected_salary_min: 7000,
    expected_salary_max: 10000,
    available_from: '2024-02-15',
    notice_period_days: 15,
    tags: ['backend', 'nodejs'],
    rating: 4,
    source: 'portal',
    source_details: 'Portal de vagas',
    referred_by: null,
    consent_data_processing: true,
    consent_given_at: '2024-01-16T10:00:00Z',
    data_retention_until: '2025-01-16',
    is_blacklisted: false,
    blacklist_reason: null,
    metadata: {},
    created_at: '2024-01-16T10:00:00Z',
    updated_at: '2024-01-16T10:00:00Z',
    created_by: 'user-2',
    updated_by: null,
  },
  {
    id: 'cand-3',
    company_id: 'company-1',
    full_name: 'Carla Oliveira',
    email: 'carla.oliveira@email.com',
    phone: '(11) 99876-5432',
    location: 'São Paulo - SP',
    linkedin_url: 'https://linkedin.com/in/carlaoliveira',
    portfolio_url: 'https://carla.design',
    current_position: 'UX/UI Designer',
    current_company: 'Design Studio',
    experience_years: 5,
    education_level: 'Superior Completo',
    skills: ['Figma', 'Adobe XD', 'Design Systems', 'User Research', 'Prototyping'],
    languages: [
      { language: 'Português', level: 'native' },
      { language: 'Inglês', level: 'intermediate' },
    ],
    resume_url: 'https://example.com/resume-carla-oliveira.pdf',
    resume_filename: 'carla-oliveira-portfolio.pdf',
    cover_letter: null,
    expected_salary_min: 7000,
    expected_salary_max: 9000,
    available_from: '2024-02-01',
    notice_period_days: 30,
    tags: ['designer', 'ux', 'senior'],
    rating: 5,
    source: 'indicacao',
    source_details: 'Indicação de funcionário',
    referred_by: 'user-3',
    consent_data_processing: true,
    consent_given_at: '2024-01-20T15:00:00Z',
    data_retention_until: '2025-01-20',
    is_blacklisted: false,
    blacklist_reason: null,
    metadata: {},
    created_at: '2024-01-20T15:00:00Z',
    updated_at: '2024-01-20T15:00:00Z',
    created_by: 'user-2',
    updated_by: null,
  },
];

// =====================================================
// APPLICATIONS
// =====================================================

export const mockApplications: ApplicationWithDetails[] = [
  {
    // JobApplication fields
    id: 'app-1',
    company_id: 'company-1',
    job_id: '1',
    candidate_id: 'cand-1',
    current_stage: 'entrevista_rh',
    previous_stage: 'triagem',
    rating: 5,
    status: 'active',
    rejection_reason: null,
    rejection_stage: null,
    rejected_at: null,
    rejected_by: null,
    hired_at: null,
    hired_by: null,
    employee_id: null,
    withdrawn_at: null,
    withdrawn_reason: null,
    applied_at: '2024-01-15T14:30:00Z',
    stage_changed_at: '2024-01-18T10:00:00Z',
    last_activity_at: '2024-01-18T10:00:00Z',
    recruiter_id: 'user-2',
    metadata: {},
    created_at: '2024-01-15T14:30:00Z',
    updated_at: '2024-01-18T10:00:00Z',

    // ApplicationWithDetails extra fields
    candidate_name: 'Ana Silva',
    candidate_email: 'ana.silva@email.com',
    candidate_phone: '(11) 98765-4321',
    candidate_location: 'São Paulo - SP',
    candidate_resume_url: 'https://example.com/resume-ana-silva.pdf',
    candidate_skills: ['React', 'Node.js', 'TypeScript', 'PostgreSQL', 'AWS'],
    candidate_global_rating: 5,
    candidate_tags: ['senior', 'full-stack', 'react'],
    job_title: 'Desenvolvedor Full Stack Sênior',
    job_code: 'DEV-001',
    job_department: 'Tecnologia',
    job_status: 'open',
    recruiter_name: 'Recruiter User',
    recruiter_email: 'recruiter@company.com',
  },
  {
    id: 'app-2',
    company_id: 'company-1',
    job_id: '1',
    candidate_id: 'cand-2',
    current_stage: 'triagem',
    previous_stage: null,
    rating: 4,
    status: 'active',
    rejection_reason: null,
    rejection_stage: null,
    rejected_at: null,
    rejected_by: null,
    hired_at: null,
    hired_by: null,
    employee_id: null,
    withdrawn_at: null,
    withdrawn_reason: null,
    applied_at: '2024-01-16T10:00:00Z',
    stage_changed_at: '2024-01-16T10:00:00Z',
    last_activity_at: '2024-01-16T10:00:00Z',
    recruiter_id: 'user-2',
    metadata: {},
    created_at: '2024-01-16T10:00:00Z',
    updated_at: '2024-01-16T10:00:00Z',

    candidate_name: 'Bruno Santos',
    candidate_email: 'bruno.santos@email.com',
    candidate_phone: '(11) 91234-5678',
    candidate_location: 'Rio de Janeiro - RJ',
    candidate_resume_url: 'https://example.com/resume-bruno-santos.pdf',
    candidate_skills: ['Node.js', 'Express', 'MongoDB', 'Docker'],
    candidate_global_rating: 4,
    candidate_tags: ['backend', 'nodejs'],
    job_title: 'Desenvolvedor Full Stack Sênior',
    job_code: 'DEV-001',
    job_department: 'Tecnologia',
    job_status: 'open',
    recruiter_name: 'Recruiter User',
    recruiter_email: 'recruiter@company.com',
  },
  {
    id: 'app-3',
    company_id: 'company-1',
    job_id: '2',
    candidate_id: 'cand-3',
    current_stage: 'proposta',
    previous_stage: 'entrevista_gestor',
    rating: 5,
    status: 'active',
    rejection_reason: null,
    rejection_stage: null,
    rejected_at: null,
    rejected_by: null,
    hired_at: null,
    hired_by: null,
    employee_id: null,
    withdrawn_at: null,
    withdrawn_reason: null,
    applied_at: '2024-01-20T15:00:00Z',
    stage_changed_at: '2024-01-25T14:00:00Z',
    last_activity_at: '2024-01-25T14:00:00Z',
    recruiter_id: 'user-2',
    metadata: {},
    created_at: '2024-01-20T15:00:00Z',
    updated_at: '2024-01-25T14:00:00Z',

    candidate_name: 'Carla Oliveira',
    candidate_email: 'carla.oliveira@email.com',
    candidate_phone: '(11) 99876-5432',
    candidate_location: 'São Paulo - SP',
    candidate_resume_url: 'https://example.com/resume-carla-oliveira.pdf',
    candidate_skills: ['Figma', 'Adobe XD', 'Design Systems', 'User Research', 'Prototyping'],
    candidate_global_rating: 5,
    candidate_tags: ['designer', 'ux', 'senior'],
    job_title: 'Product Designer',
    job_code: 'DES-001',
    job_department: 'Design',
    job_status: 'open',
    recruiter_name: 'Recruiter User',
    recruiter_email: 'recruiter@company.com',
  },
];
